trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'employee-api'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'

- task: Docker@2
  inputs:
    containerRegistry: '<Your-Azure-Container-Registry-Service-Connection>'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '<Your-Azure-Subscription>'
    azureResourceGroup: '<Your-RG>'
    kubernetesCluster: '<Your-AKS-Cluster>'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'k8s/'
